clear;
clc;
close all;

N=100;

a = 0;
b = 2*pi;

dx = (b-a)/N;
x = a + (0:N-1)*dx;

f = exp(sin(x));
d2f = exp(sin(x)).*(cos(x).^2-sin(x));
d2f_approx = (circshift(f,-1) - 2*f + circshift(f,1))/dx^2;

%% Plot exact and numerical derivatives

fs = 24;

% Okabe-Ito colorblind-safe colors
cols = [ ...
      0 114 178;    % blue
    230 159   0 ... % orange
    ] / 255;

fig = figure( ...
    'Theme', 'light', ...
    'Position', [100 100 1200 800]);

hold on

% Exact derivative: continuous curve
plot(x, d2f, '-', ...
    'Color', cols(1,:), ...
    'LineWidth', 3, ...
    'DisplayName', 'Exact $f''''(x)$');

% Numerical derivative: markers distinguish discrete data
plot(x(1:3:end), d2f_approx(1:3:end), '--o', ...
    'Color', cols(2,:), ...
    'LineWidth', 2, ...
    'MarkerSize', 8, ...
    'MarkerEdgeColor', cols(2,:), ...
    'MarkerFaceColor', 'white', ...
    'DisplayName', 'Finite difference');

% Axis formatting
ax = gca;

set(ax, ...
    'LineWidth', 2, ...
    'FontSize', fs, ...
    'TickLabelInterpreter', 'latex');

grid on
box on

xlabel('$x$', ...
    'Interpreter', 'latex', ...
    'FontSize', fs);

ylabel('$f''''(x)$', ...
    'Interpreter', 'latex', ...
    'FontSize', fs);

title('Second Derivative of $f(x)=e^{\sin(x)}$', ...
    'Interpreter', 'latex', ...
    'FontSize', fs);

legend( ...
    'Location', 'northeast', ...
    'Interpreter', 'latex', ...
    'FontSize', 0.75*fs);

xlim([0 2*pi]);

xticks([0 pi/2 pi 3*pi/2 2*pi]);
xticklabels({'$0$', '$\pi/2$', '$\pi$', ...
             '$3\pi/2$', '$2\pi$'});

hold off

% Export for LaTeX
exportgraphics(fig, 'secondDerivative.pdf', ...
    'ContentType', 'vector');


%% Part B

Ns = 2.^(3:10);

errInf = zeros(size(Ns));
errL2  = zeros(size(Ns));

for k = 1:length(Ns)

    N = Ns(k);
    dx = (b-a)/N;
    x = a + (0:N-1)*dx;
    f = exp(sin(x));
    d2f = exp(sin(x)).*(cos(x).^2 - sin(x));

    % Periodic second-order centered difference
    d2f_approx = (circshift(f,-1) - 2*f + circshift(f,1))/dx^2;

    % Error
    e = d2f - d2f_approx;

    % Relative infinity-norm error
    errInf(k) = norm(e, inf)/norm(d2f, inf);

    % Relative L2 error
    errL2(k) = norm(e, 2)/norm(d2f, 2);

end


%% Log-log convergence plot

fig2 = figure( ...
    'Theme', 'light', ...
    'Position', [100 100 1200 800]);

hold on

loglog(Ns, errInf, '-o', ...
    'Color', cols(1,:), ...
    'LineWidth', 2, ...
    'MarkerSize', 9, ...
    'MarkerFaceColor', 'white', ...
    'DisplayName', '$L^\infty$ error');

loglog(Ns, errL2, '--s', ...
    'Color', cols(2,:), ...
    'LineWidth', 2, ...
    'MarkerSize', 9, ...
    'MarkerFaceColor', 'white', ...
    'DisplayName', '$L^2$ error');

ax = gca;

set(ax, ...
    'XScale', 'log', ...
    'YScale', 'log', ...
    'LineWidth', 2, ...
    'FontSize', fs, ...
    'TickLabelInterpreter', 'latex');

grid on
box on

xlabel('$N$', ...
    'Interpreter', 'latex', ...
    'FontSize', fs);

ylabel('Relative Error', ...
    'Interpreter', 'latex', ...
    'FontSize', fs);

title('Second Derivative Convergence', ...
    'Interpreter', 'latex', ...
    'FontSize', fs);

legend( ...
    'Location', 'northeast', ...
    'Interpreter', 'latex', ...
    'FontSize', 0.75*fs);

hold off

% Export for LaTeX
exportgraphics(fig2, 'secondDerivativeConvergence.pdf', ...
    'ContentType', 'vector');
